# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfRegistration', models.DateTimeField(auto_now_add=True)),
                ('mobileNo', models.CharField(db_index=True, max_length=255, unique=True)),
                ('emailId', models.EmailField(db_index=True, max_length=255)),
            ],
        ),
    ]
